layout_spectrum: 0.746254
color:
  saturation: 0.9597207
  brandStrength: 1
  lightness: 0.7416756
  brandColors:
    - '#FFFFFF'
    - '#14C5F1'
    - '#8197A2'
    - '#043145'
    - '#42677A'
  rhythmicContrast: 0.537594
typography_spectrum: 0.3897659
name: Deus Images
